# ===== LOCAL (Ollama) =====
spring:
  config:
    activate:
      on-profile: local
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        enabled: false
        options:
          # choose one you've pulled locally (see step 3)
          model: mistral:instruct
          temperature: 0.2
      embedding:
        options:
          # runs locally in Ollama too
          model: nomic-embed-text
    vectorstore:
      pgvector:
        initialize-schema: true
        dimensions: 768
        distance-type: COSINE_DISTANCE
        index-type: HNSW