# ===== CLOUD (Groq) =====
spring:
  config:
    activate:
      on-profile: cloud
  ai:
    disabled-openai:
      api-key: ${GROQ_API_KEY}
      base-url: https://api.groq.com/openai
      chat:
        options:
          model: llama-3.3-70b-versatile
          temperature: 0.0
    embedding:
      options:
        model: nomic-embed-text-v1
    vectorstore:
      pgvector:
        initialize-schema: true
        dimensions: 768
        distance-type: COSINE
        index-type: HNSW